# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Running build...
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:  
  files:  
    - "**/*"
    - 'dist/**/*'
    - 'node_modules**/*'
    - 'package.json'
    - 'package-lock.json'
